// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqkwmhqqezstamhpmghe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xa3dtaHFxZXpzdGFtaHBtZ2hlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM2Mjk0MDAsImV4cCI6MjA4OTIwNTQwMH0.xW0vryCiwXR8hKiQa_hehwfyXzqD_92o0Qltd9Yh3-I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});